model: triplet_reid.edflow_implementations.implementations.EdflowModel
dataset: triplet_reid.edflow_implementations.data.QueryGalleryNTU
iterator: triplet_reid.edflow_implementations.implementations.Evaluator

batch_size: 16
spatial_size: 256
n_data_processes: 16
