model: triplet_reid.edflow_implementations.implementations.pretrainedReIdModel
dataset: hbu_journal.data.prjoti.PretrainDataset
iterator: triplet_reid.edflow_implementations.implementations.getReIdEvaluator

batch_size: 16
spatial_size: 128
box_factor: 1
bottleneck_factor: 2

hook_freq: 1
log_freq: 250
ckpt_freq: 1000
test_freq: 1000
num_epochs: 1
