model: triplet_reid.edflow_implementations.implementations.EdflowModel

dataset: triplet_reid.edflow_implementations.deepfashion.data.Eval
data_root: data/deepfashion/images
data_query_csv: data/deepfashion/query.csv
data_gallery_csv: data/deepfashion/gallery.csv

iterator: triplet_reid.edflow_implementations.implementations.Evaluator

batch_size: 16
spatial_size: 256
n_data_processes: 2
